# 79. __name__ and "__main__"

<details>
  <summary> Section 9: Modules and Packages - 79. __name__ and "__main__" </summary>

<p align="center" >
    <img src="https://python-ds.s3.us-west-1.amazonaws.com/The-Complete-Python-Bootcamp-From-Zero-to-Hero-in-Python/imgs/79__main__.png" width="90%" > 
    <img src="https://python-ds.s3.us-west-1.amazonaws.com/The-Complete-Python-Bootcamp-From-Zero-to-Hero-in-Python/imgs/79__main___2.png" width="90%" >     
    <img src="https://python-ds.s3.us-west-1.amazonaws.com/The-Complete-Python-Bootcamp-From-Zero-to-Hero-in-Python/imgs/79__main___3.png" width="90%" >     
    <img src="https://python-ds.s3.us-west-1.amazonaws.com/The-Complete-Python-Bootcamp-From-Zero-to-Hero-in-Python/imgs/79__main___4.png" width="90%" >     

</p> 

</details> 

<details>
  <summary> 79. __name__ and "__main__" </summary>

-   [Notebook: 01-Name_and_Main](https://github.com/BloomTech-DS/Complete-Python-3-Bootcamp/tree/master/06-Modules%20and%20Packages/01-Name_and_Main)

-   [Codebase: 03-__main__](../../../codebase/python-camp/06-Modules-and-Packages/03-__main__/)

</details> 





---

[Previous](./78_Modules-and-Packages.md) | [Next](./80_Errors-and-Exception-Handling.md)